# Generated by Django 4.2.4 on 2023-08-22 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guidy',
            fields=[
                ('guide_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=255)),
                ('link', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Stewardesses',
            fields=[
                ('nr_ewidencyjny', models.TextField(primary_key=True, serialize=False)),
                ('imie', models.TextField(max_length=255)),
                ('nazwisko', models.TextField(max_length=255)),
                ('crewlink_id', models.TextField(max_length=255)),
                ('crewlink_password', models.TextField(max_length=255)),
                ('LOT_password', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=255)),
                ('text', models.TextField(max_length=5000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artykuly',
            fields=[
                ('artykul_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=255)),
                ('text', models.TextField(max_length=5000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artykuly', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
